services:
  api_crud_products.anguar:
    image: ${DOCKER_REGISTRY-}apicrudproductsanguar
    build:
      context: .
      dockerfile: backend/API_CRUD_Products.Anguar/API_CRUD_Products.Anguar/Dockerfile
